/* XPM */
static char *a86339f62cea4a88900bce87f0eeef73vY60V3fnoxx2zMAA[] = {
/* columns rows colors chars-per-pixel */
"128 128 179 2 ",
"   c #000000",
".  c #090706",
"X  c #090807",
"o  c #0C0A09",
"O  c #110E0C",
"+  c #14100F",
"@  c #171411",
"#  c #1B1613",
"$  c #1F1916",
"%  c #1E1B19",
"&  c #201A17",
"*  c #231D1A",
"=  c #26201D",
"-  c #29221E",
";  c #2E2520",
":  c #302622",
">  c #332A25",
",  c #3A2D25",
"<  c #392F2A",
"1  c #3C322C",
"2  c #3D3631",
"3  c #43342D",
"4  c #433630",
"5  c #453A35",
"6  c #4A3C35",
"7  c #463E3A",
"8  c #4B3F39",
"9  c #513F35",
"0  c #503F38",
"q  c #4F4037",
"w  c #47413C",
"e  c #4B433E",
"r  c #544137",
"t  c #53453D",
"y  c #59463E",
"u  c #5C483F",
"i  c #61473A",
"p  c #614A3F",
"a  c #4D4641",
"s  c #4E4843",
"d  c #534741",
"f  c #584740",
"g  c #544943",
"h  c #5C4B43",
"j  c #554E49",
"k  c #5B4F48",
"l  c #56524D",
"z  c #5C524C",
"x  c #575550",
"c  c #5A5651",
"v  c #5C5955",
"b  c #5F5D58",
"n  c #614E45",
"m  c #694F45",
"M  c #604F48",
"N  c #635047",
"B  c #695246",
"V  c #64524A",
"C  c #69554C",
"Z  c #6D584F",
"A  c #71574A",
"S  c #725A4F",
"D  c #635750",
"F  c #695750",
"G  c #635A54",
"H  c #6C5B53",
"J  c #625E5A",
"K  c #6A5F59",
"L  c #725F57",
"P  c #705D55",
"I  c #725D53",
"U  c #7A5E50",
"Y  c #705F58",
"T  c #6D6057",
"R  c #63615C",
"E  c #63615D",
"W  c #64615D",
"Q  c #64625D",
"!  c #65635D",
"~  c #66635D",
"^  c #64625E",
"/  c #65625E",
"(  c #65635E",
")  c #65635F",
"_  c #66635E",
"`  c #66645F",
"'  c #64625D",
"]  c #69615B",
"[  c #6D615A",
"{  c #69615C",
"}  c #68635E",
"|  c #6C645F",
" . c #6C625C",
".. c #736057",
"X. c #796257",
"o. c #72625B",
"O. c #73645C",
"+. c #79655C",
"@. c #7C685E",
"#. c #666460",
"$. c #676560",
"%. c #676561",
"&. c #676560",
"*. c #686561",
"=. c #6B6560",
"-. c #686661",
";. c #696661",
":. c #696762",
">. c #696763",
",. c #6A6763",
"<. c #696662",
"1. c #696863",
"2. c #6A6863",
"3. c #6B6965",
"4. c #6B6A65",
"5. c #6C6964",
"6. c #6C6A65",
"7. c #6C6A66",
"8. c #6D6B67",
"9. c #6F6C67",
"0. c #6D6A65",
"q. c #6E6C68",
"w. c #6F6D69",
"e. c #6F6D68",
"r. c #6F6E69",
"t. c #6F6D68",
"y. c #736760",
"u. c #796760",
"i. c #776962",
"p. c #706964",
"a. c #706A65",
"s. c #736B65",
"d. c #726B66",
"f. c #736B66",
"g. c #716C67",
"h. c #736C66",
"j. c #746D67",
"k. c #746C66",
"l. c #766D67",
"z. c #726B65",
"x. c #7C6C64",
"c. c #7A6B63",
"v. c #736D68",
"b. c #706E69",
"n. c #716F6A",
"m. c #716F6B",
"M. c #726F6A",
"N. c #756D68",
"B. c #746E69",
"V. c #746F6A",
"C. c #756F6A",
"Z. c #746E6A",
"A. c #726E69",
"S. c #72706B",
"D. c #76706B",
"F. c #72706C",
"G. c #74726D",
"H. c #76726D",
"J. c #75736E",
"K. c #77756F",
"L. c #74716C",
"P. c #79706B",
"I. c #78716C",
"U. c #78726D",
"Y. c #78746F",
"T. c #7E756F",
"R. c #7A726D",
"E. c #777570",
"W. c #787671",
"Q. c #797671",
"!. c #7D7B76",
"~. c #7C7974",
"^. c #7F7E79",
"/. c #826D63",
"(. c #817C77",
"). c #807E79",
"_. c #82817C",
"`. c #898781",
"'. c #8A8883",
/* pixels */
"n.w.8.>.n.K.9.#.>.R ` #.R Q >.#.Q Q >.>.Q Q Q Q Q Q 1.#.w.n.8.>.#.#.8.1.>.J #.>.Q Q Q Q Q Q Q R R #.8.S.8.n.8.w.H.w.4.Q R Q Q 4.Q b b J Q Q >.8.w.9.8.H.H.S.w.w.w.n.w.} z t t t d h G s.P.K N k h t t h t k k y h t t t y t t y V y t h t t t y h t t n N D ] w.",
"s.s.s.g.H.'.Y.>.z g t t d t t t t t g h t t t t t h V K K C N k t h g d h h t k t t t t t t t g z | n.C.C.C.n.C.C.D.s.h g t t h g z } n.n.!.8.C.I.s.j.j.s.s.g.j.C.T.k h n n n n n n n n C V n B n V C n C I n n n n n n n n n C I B h n n n V n n n N n C h N D ",
"N N 6 D j.w.I.z h h h k C k h k k t k N h k N k h k V x.V I V V V C k H V h h h h h h h h h k h h h k N n n k k k h h k h 9 k k h k G 8.>.W.>.[ y N n h V n h n h h n h n n n n n V n n V V V N N V N y N n n n n n n n h n h V B B n n n h n n V n n n n V C n ",
"n n N n V 4.z i.k h h h h F k h k N k N h k h k k C V Z Z H C k h k k k V k h h h k h h h k h h k N o.3 h N n n n N k F k M N k C h t J >.Q J y V N n n V N h r y h h h n n h n n n V n n n N u C V V N n n N n n n n h n n n n B C n Z V n n n n n V n B n C V ",
"C n N n N >.z N V k C h k k k k h k n N h k k h N n N Z N h k k k k k h k k k k k h h h y k C F C n n V ..h k h H N V V N N V h n h h z 1.Q D n Z I o.N n C n h h n h u n n n n n N n C n n n n N C V N n n V n n n n n n n n n C N V n n h h 6 h V V N n N n V ",
"V Z C Z N ` h N N V k Z n N k N h k y k k h V O.h h r h F y k k k k k k o.k k y r k k k n N n Y n n C V N k h N h C H h h k n y h h k z 1.Q c N V n o.N I n +.I n y n y h n n n N o.V V V n h y n n V N n n C o.n n n n n 3 n n C N B n n h h n n r n V n h N n ",
"N n n Z o.#.h u k k n n k n k n n y C h k h V N h h y N N h y N k k k C k N N N k k k k n V C V H n n r k N k N ..k n C h k h y h h f l Q J c N h 9 V V n B B I 6 u h h h n u N n V n N n n n h C n n N h V n n n n n h n n N C C B Z C n h h n h n N n n n n V ",
"N N n V k Q h k k h k h N k k h h h k k k k N n h h k h N h k h N F n N n V n h k k k k h C n N N C n h n k n k N y k h V k h h f h h z ` Q c n h n n H I X.C L n n h n u n H Z V n n n h N n h n n n n n n N n n n n n N o.C Z Z B B B n n n n n n n n n N n n ",
"C n C N N R h k n n k h n k N k k k C N k N C n h k h V h h k k k n k h t k h k k N h h t n N N V V n k k k k V k h k h h h k h h N h z J } G I n n n C B B B h n n n n n n n n n h N n n n n n n n V V n n n I n n n h h N V I B V C V C n n n h n n n N n n V ",
"V H V N k ` h k N V k h h k h y h N V h N k n V N h h h h n h k h k h n k k k k k h h n h h k V V 4 r N N h k k k N C h h h t h h h y z ` >.D S n n C Z C C B V n u n n V y h h n n n n n h n n V V B C n I n n h n n n h N B n B n C B N n n n n n n n V 4 n C ",
"N I C N C Q g k N n n n h h h h h k N h n h V h h h u h N h k k k k O.h k k n k k h k h h f k C h h h y V N h k k k n h h h h h h h h D G R z V h n u C Z B n V n n h u y y n B n y C V N h n n n I n n C V n h n n n n n N N B C n n n n V n n n n n n n V c.V ",
"n y Z I H >.h h k h k k k k h N N V h k h k k h h h r C N h k h k h k V k k k N k k C h h h h h h h h h h h h k k h h h h h h n 4 h h z b Q z V n n r V Z S n n h h n n n y u.N n n V @.y n n V n n n h V V n n h n h n n B B Z B n n h N n n n n n n n n n C n ",
"C Z h B C Q h k h k k k h k h N n n V k h k h h h h y y h h k k h k h V N h N k n n h h k k k h h N h h Z n k h k h h k k h k k h h h g R Q z n n h n C r n V h y n n C N h N n n n n /.V n h n n n n h n n N n n n n n n I C A B n n n h h n n n n V n n C C y ",
"V N Z X.N Q h h n k k k h k h N C Z n h h k h V h h y h h h h k k h n V k k u n k k h t h n h y h h h k F k k k k h h h k h k h k k k h G Q z n n n h V h n n n n n B n C 6 h n h n n n n n n h n n V n n n n n n n n N n n Z I B n n n n n N n r n n V n I n V ",
"V n n Z H Q h h h h k k h h h V V y H k h h k h k h h h h h k k k n C y N n N k h n h h h h k h h h h k C k h n F h C N k k h N k h N n D Q k h y N C n n n n u u r n C n u h n n n n n h n n n n n n n n n h V n n n n n N B N B n n n n h n h n n n Z n n n n ",
"n n n V k Q N k M h k h k k k h h h O.y k y N h h k k k N k k n k n , h k k n k k k h h y t y h y y h H h h h k k k n H h k k n t h k V k J h V n @.n n h n h n n N n B n n n u h n h n V n n n N N n V h h n h N u n h n n n C B n h n n h n n V n V C V n n n ",
"N V n V C Q N n k k k k k M N h N h V Z F h h n C C h h k h k N k k k k t k k h h k k h h h t h 9 r h V t h h N h N k k h N h k h n h t V 8.H n B h C h h n n n n n n V n n n n n h n n n n n n V V n n n n n h N n h n n n n n N n n n n n n n n V n h n n n N ",
"N V n n C Q k k k h h k h k h C C N h n h h h h h h k h h h h k k k h h k y V N k h h y t t t h V h k k n V n k C h h h h k h N h h k h h J N B n n h N n n h n n h h n n n h n V n n n n V n n V N h n n n N n n n n n n n n h h n n n n n n n V N n n n n n n ",
"n n I k z J h k N t M h k n C V 6 h h h k k k k k h k k k k k k k , h k k h k N k h h h h h t y 9 C h h k n k h h k N h h O.N N h k h h k x j k H o.h V n n n h h V n C n h n n n V n n n N N C C C B V n n h n n h n n n n h h C n N V n n h N y V n n n n n I ",
"d d s j l v j N h h 6 k k h h h F h N k N C C O.n h k h h h h h k k k N k h k F n k k t t t t h y h h C h h h k h k k N h h N k k k k V j l l j s d a a a e e a e a g j e e e a a a a a a d e d j d k g a a s a e e e a a a e d j V F H H C z k j d a g a d a d ",
"v b J J E ` G z z [  .[ z g d d N D H H H i.c.H D i.O.K O.[ O.[ O.K V z j j g j j d d g h K O.O.i.o.O.y.H c.y.[ O.O.O.[ [ O.O.H H O.D j l v b v x v x v v j s s s J Q Q l x x v b v x l c c x J Q Q J v v x x c x x x c c c v v v ` 9.#.R J v J x v v v x v v v ",
"n.F.w.n.W.!.w.>.J Q Q R v v x l c b 4.8.9.8.>.Q Q Q Q Q R Q >.Q Q Q E J v E ` >.x c J c c J Q Q ` J R #.` n.>.9._.#.Q R Q Q Q R 8.4.9.Q 1.w.K.H.F.F.w.>.#.J ` D.Y.D.S.K.n.>.8.H.Q.(.F.w.n.8.n.n.F.H.W.Q.n.w.8.8.8.w.n.8.w.H.S.F.F.} z h h z =.9.1.w.S.n.H.n.n.n.",
"D.I.s.C.C.C.p.h t t t k c v b b v v z d s a 7 7 e 7 w 7 7 7 e 7 w a l >.F.W.W.H.H.S.n.J j a e 5 7 e 7 a g d g a g 7 7 7 7 7 w w e a g g J 8.8.8.8.8.9.>.8.4.!.`.Y.~.I.C.s.5.5.C.I.j.P.=.s.s.g.C.C.C.j.j.=.5.s.5.s.s.s.s.s.s.s.j.D h f h h N n z p.s.g.s.C.] g.g.",
"n k h k n h h h k h h k V v R v J z d d n d a l g g j j z j s a g j j k v 5.4.n.H.n.j e e 2 7 5 e g j g g j e a e a a a g a a a a e a a a g e a e a a 2 v Q n.!.s.] r y h h h h h n n h r h h h y h r y h r t y h t h h h h y N h k n k N n n k h n k k h n h k ",
"k k k h h h k k C h n n y v R Q x 7 g g ; y e e a g j k g j a a j j G p.7 a e e a g a e e e e e e a a j j e e a a e a a a a a a a e a a g g a g e a d a 7 v #.1.~ h V y h h h y y t h h h y h h y h t k y C t h t h y h n n y h h y t y h k H k h h h h h h h h ",
"k N t h k h h h h h N n t l R R x g a e e e a e } d e a d e j e g d a e e e a a a a a e e e a e w a a g a a d a a a a s a s g a a e e a 5 a a a a a a a a l Q 1.G V V h y h t h h h y h n n k h h h h y t h y t h t h n n y h h h F u y h h k k h n n h h h h h ",
"h h k h k n h k n n h h h z J J l a e a e a a s a a e e e e e e a a e a e a e a a a a a e g a w e s a s a a g a a a a a a g g g a a 7 e a a e d a a a a c x #.1.z h h h V V h N n h h h r @.k y r h h t k h n h h n C h h y h h h n h y k k k N n n k n h h h k ",
"n n k h k N k V n h k k k l E R l w e e e e a a j a a a a g a a a e a g a a a w a a a a e s a a a a s a a d g a a g a a a d g a a j g a e a 7 s g g J e g x Q ` c k h h h h V C N k h h h 3 y h y h y y h h N y t h n 4 t h h n n h n k h h h V h n h h h h Z k ",
"y h n h h n h C h y h N y z b E l e e g e a a j j e j a a e e d s a a d a s d a e a e e e a e a a a a a a a d s d a a g g s g a a k k a g a 5 e e z j j g l b b z h h h h k y Z B k h h K h y h y y n h h F h y y y t r f n h y k k h h h N N h h h h n h n h h ",
"h N k n 6 h n h k n k n h z R J j a a a g a a d g w a a e e a a e a a g a e g a a d a a e e a a a e e a a e g 7 s a s w s a a a g g g j s g d g d j d 1 e x Q J H h h y h h V n V h h h h y h y y y h n n n y y h h n y h V k h k h h h C C h k k k n n h h k N ",
"h n N V h h h h k h h n h z b v l e e w 5 a g e a e a g e e e e a a a a a e d a a e a a e e a a e e a e s g a a a a a a e a s 5 g d j 5 e d j g j t a a g l v #.z h h h h h C n n y h h h h y y h h r h C u y n y n V h n n h h h h N C C V h N k n h n h k h h ",
"V N V C h n h h B t y N h z Q E l e a e 7 e a a a d d a g 7 a e a a a a e e g g e 2 e e e e e g z 5 a e e e g a a a a g g a a j g j g a e a k e w a a a j x 8.1.D N h h h H n N n N h n h h n h h y y y C y 9 n n 4 h h N h 8 h k h H V k h h h h h h k h h k k ",
"N N V n k h h h n k n t h c Q J l w 5 e s e a a g g s e e a 5 a e g a a d a a g e w e w e 7 w g s a s e a a a e s a a a a e j j g g g a a e a e a a e e a x >.1.G N V n o.n B Z H V n n n N B V k y t y y h n r y h B h y k h n h n C h h k h h h h k h h h h n ",
"V N V h c.k h h h k h h k v R J l e a e 7 w a j g g z e e e w a j a g e g g j z j e w e e e a j j j a a e a a e a a a a s a j g j j g e e e a a 7 a a a a x R E G h V n V y n C C V C I n C B h y y h y n h k h h h t t h h h n h h n V N k k h h h h h k h h k ",
"n k k n n h n h k h h h h J R b l e e e e e a a g a e e a e g e a a d d e j z j a g e e e e 4 d j z d g e a a d a a s d g a e a 7 a a e e a e a a a a a a l b J z k C V N C H I C n V V C /.n k k y h y h N n N k h h h h k C y h k n y h h n k h y n h n N k h ",
"N n h h h N n h n k k N y l J E l w e e a j w e w g g a a a a e J a a 7 d a a a e e e e w e g g g j g a e a a j a s d g d e a g g a e e e a a e a a e e e l Q R v h k V n L Z V I Z N V n y k h y h N h I B n V n y k n h k h h h k h h h h h h y h k k n h h O.",
"h N k h h n k V k h n C I c 4.b l w w a a a l e a e e a w j a e a s a j z a g a w e a 7 e e a g g 5 e a a e a a a a a a d j j g j a e 7 a a e a 5 1 a a a x J Q z y h k h V I C C C L B n h h h h h N n V o.h n 3 h n h C k k h h f k y h F h h y h h h k h k h ",
"n h k k h h k C h h h V y D >.R l e w e e e a a e g a a a x 7 s a J j j g e e e a e w w e e e e e a a e e a a e e a a a e a g z g g a a a a z a a a a e g x J J z h V k h V V C r C y n V C k h n k h n V C V n C C V k h h n V o.k N F n k n h h h h h k k h h ",
"k h h h k h k n n C N h y z >.>.l a e a e e g a e e e e e a a a a a s e a e a e e s a e e e e e e a e a a a a e e a a a d a 7 j g j a a a a e a a a e e a l b Q z h h k k h N V N C H V C C h V i.h h h n n n t h V y h h h k V n N C h B C h h y h k k n h k k ",
"k k h h k h k h k h n k k k G E j e a a a e j g g e a w e e e a e a 7 g g 7 g a e d e e e e e 7 e a a g J a e e 1 a g g a a e t e e e a e a e g a a a e a l J J z h k N k h k n y C V u V V n N k h h h r V h h h y u u y h k n n n N V N u V h h h h h h n N k ",
"g d a s a a g h k k h V V z z b j j e e a a 5 a a w e a a a w e e g a 5 e a a a e a e e e a g e a a a d g a a a a a a a a g e g e d a a g s a z e d a a s l v J l h n n k k h h h k C V t y h k N n N h h h y V C h h h h y h h k V j g e g j a a g g a s a a g ",
"b v v x J x x x z D V V h j z v x j j j s a a s s a e a a s w a a s s a a a a a e j a e 7 a e a z a a a a a a g j a a a a a s a a a e s s s s a a j v j l x R Q J h z F D O.[ [ O.[ O.o.C i.H o.H O.O.o.O.H F O.C O.O.O.O.[ V z z [ l c G v v v v v x v c v J v ",
">.8.8.9.w.w.n.4.n.4.R E R Q >.4.8.>.#.b x x x c c v v x v v x v v b b b l v v b v x j j j l } J Q c Q z Q v l l x x v v j l l l x x x c J v b b v J Q Q >.n.E.!.9.>.>.>.` E E E Q Q 1.` >.#.` 1.4.8.n.J J ` ` E | 8.w.#.Q Q Q 8.8.s.8.1.n.w.w.H.K.n.8.8.x.>.1.w.",
"W.I.D.C.g.C.P.I.H F k t h k z D H C N K J 4.4.9.4.8.8.8.w.w.n.n.F.~.~.H.F.w.S.F.9.w.>.R Q >.>.>.#.Q Q ` R J ` #.n.F.~ 8.>.9.n.` 4.>.S.F.E.9.n.F.~ z d t z z C.k.G z g t t t t t t t g y k t h N k d h t t t t t t h t q C t 8 h z y.s.n.C.g.C.C.j.C.C.P.n.n.W.W.",
"T h C k h C V Z Z C V h n n n N n h C V I V p.j.s.C.s.s.g.C.s.D.D.D.I.C.C.g.C.P.p.=.e 5 h N h h h t t t h h k [ k.C.s.8.w.!.Q.8.D.C.C.C.D.y.C.z h h y h h k y h k N h k k k h h h k n V n h N C V n H V F y B h h h n n +.n V k h h h h h N F h k H t 6 K C.`.Q.",
"H N C n k n Z , Z C V V n n n B N n I Z B n n n n n n n n n n n N V n N V Z N h h 6   X B n n N V n n n n n V n V V n  .>.w.S.Q K 6 h h h V h n h h h k k h h k n k 4 ; 1 k h h h h h k 1 ; ; 5 n V N V h h h k h h h h Z N n I k n k N n h n k k C N t V D E.K ",
"C C C V h n h H V C C N n n n V n n n C Z H h h h n h n h C n n N V N n V C C N N 6   . I B V y N N n & @ t V N N n C i J #.Q v t k N h h h k h V h k C k h h h h 4 *   # h h h k h h t       & N C C h h h n n h h h N h F V N t N n k n N N y k V k n h N 9.C ",
"I n n 6 V n y h n B N N V n n n n n n h n h V u n h n H n V C V n V V N N n N n n 6   . I C N n n n n .   6 V k n n n C J R Q z h k k h h h t h h k k h k h h h h k *   # k h t h h y *       * n u u h k h h t h y N h h h V ..h k h k t 9 h h h h V k C F >.V ",
"n h n N n h h k n N Z V n n n n n n n V n n n h n n x.h C n n C V N n N n n N F n 6   X Z C N N n n H .   5 n N N n H L G b J l h h h h k h h k t H N k h h h k k h *   # h h h h k q     o   & n h V h h h y h h u r h h h n n k k k k h h h h k N n V C n n.C ",
"n F n n n V n n n N n h n n n N n n @.n n n n h I n n V N n h h V n n t 1 1 5 n V t   . H y V n N V n .   5 n t : 1 y V G #.v z h h h n n N t 5 > 1 h h h h h k n n *   # k k h y k &   # $   & n h h n h t h h y h h h h n k h h h h h n h h h h t h h h K J h ",
"V H Z Z C C n n N h h n n h n n n C n n h n h n V h C V N n n n N C 6         . 4 8   X Z h 3               o 1       ; l     a h h h h h 1           + V N k h k n *   # k h k k 8     8 &   & h h h k h k h h h h h h h k k k k h h h h k h h h h k k h h Q h ",
"V B B n n h n n n n N n h n n h n h n n V n n n n n N V h n n n H 4     o - - +   -   . N n t : > : :     * 3 1 ; ; #   *     a h F k h *     @ - * X   . 8 h k N n *   # k h h h #   * h &   & k y h h h k k h h h h h h h h h N k h h k h h h h k h h N h Q N ",
"V C Z n n n n r n n n k n n n n h H n N V V n n n n n V n V h C V &   # H V N N 3     . n n n n h h n .   6 n y n V V 5       g h N k 6     4 h h k y O   # h V h h *   @ h k F 6     t k $   & h h N h h h k O.h M h k k n k h y n h h h h h h h h k h h k >.k ",
"V C Z n n h n h n n N n n n n h n n V V n h n n h n h N C C H V n o   5 V V n n n $   X V n N h V u V X   5 h n n N N n =     e t h n O   * h h h k h 8     5 n h k *   # N C N @   * t k &   $ h f y h h N H N N N k h h C k h k t n h h h y h k k k k h n >.N ",
"V n n n N n n h n n C B t n n n n n C n n n n h n n n C N V C y n     t V V n n n 1   . C N V n n u V .   6 n N V V V n w     a h k t     6 h t h h h h +   - h h k *   $ k n 5     t h h &   & y y y y N V n n n n h n k n n h k h k n h k h h n h h n h z Q N ",
"n n n h y n k h n n n n C n n n h N N n n n h n n n N n y B Z h h     n V n n V n 6   . n V V V n V N X   6 N C V C n n z     a h N d     t h N k V k h $   $ h h k *   $ 4 Z +   ; h h h =   & y h h h n n n N n N H y k n C h N k k h k h k h V k n y k z E N ",
"V N n n n n n h y h n h n n n n n n y n h h h h h n n n N n V N y     F C V n V n t   . V V n C V Z V .   q C C C Z V n x     w h V 6     h k h h V n h *   @ k k n *   $ h 5     N h k n =   $ h h h h h V V n H N h h h h 6 V k y h h h k h N V k k h t j c D ",
"n t N n V n n n k k n h h n N h N n N k n n h h n n n V V V V n h     n V V n n n 4   . V H V n V C n .   6 Z B Z N V n z     a h h t     t h h h h h N $   * h H t *   $ N o   > N V C n &   & h h h h h N V V n n h h k h h V N h h h h k k h Z h k k z v v z ",
"n n n n n n n n n N h k h h C C C V n h k n n V n n V n V V B n h     h V V n n N 6   . N n N N V V N .   6 C C C V V n c     a h h N     5 k h h y h h +   : n N k *   @ 1   . C C V V N &   $ h h h h h h n V n h h h h y h k N N k k h k h h n k N N z v v z ",
"N n n n n n V n h n n h n n Z B C N n n h n V n N C n n V C n n V     h V V N N V 5   . V V N V V V V     t Z C V H N V c     a h n h @   - h h h h h q     h n h h -   @ o   < N V V n h &   & h h h h h k h V n n h h h h h h k n N h h h N n F C C V z v J z ",
"n N n n h n n n h n n n n H C C H n h n n n N h n V n n V I C N h     k V Z C N B 6   . V V V V N N 6     h V h n N n n z     a N n h 6     1 h 0 h t @   * r k h H *       o V V n n k y *   & h h h h h C N N V n k h h h k h h h C V n C k C N C V V z b J c ",
"z n n h k n N r N n k n n n V V N n h h N n V V 4 n n n I Z n N h     h N H ..n n 6   . V V 6 @ @ X     $ n n V N n u n v     w k h h k =     # - & .   o h h h h h *       1 h V H n n 9 &   & V y n y k V V H h h h h h h h h k h k k k C n n V V V z J >.Q c ",
"z z F O.O.y.o.D k g d g d g s g a e a g a a a g d d a s g s s g w     d V N B C n 4   . V V 3     . + > h N N V V n V z x     w h k k k h 4 +       . = a d a a e s %     o j g j g g j e $   % j j h g a g a a a a a s s a a g g k V K [ y.c.N O.o.D z >.Q 1.J ",
"R Q J Q R Q !.J v x x v c v J v x x v E v v v J E x l l l x x x b x v J J z V V j v z V K o.O.O.i.F O.O.o.x.O.c.O.O.V z l 4.J l j k D [ z j x x a j v } v J x v x G J v x x b J v v v l l l v v J J J J J x x v x v J v x c x v v v J Q #.R Q Q Q 8.#.4.w.F._.4.",
"d w 7 w 7 e d j J >.w.w.w.w.S.8.8.F.8.F.n.w.n.S.>.8.1.9.H.n.>.4.n.w.n.E.8.#.R Q R Q Q Q Q >.>.` >.>.Q ` #.Q #.9.1.Q #.8.n.!.~.w.>.Q Q #.Q R #.>.w.w.8.n.H.E.S.8.n.E.n.8.8.8.8.4.4.>.#.>.8.D.n.n.H.E.H.w.n.4.8.8.n.9.w.n.n.9.8.n.F.8.z e e e w w e d e z 5.=.g.Q ",
"t d e e d d g t e j 5.n.8.8.n.8.n.8.n.s.g.H.n.n.8.8.8.K.W.W.H.n.g.g.D.H.=.l j g g z g d t e e e g e q q e t d g g e j j | I.I.C.D d t e g z =.s.s.8.8.s.8.n.n.8.R.H.n.n.8.n.s.8.=.8.8.W.Q.9.w.D.n.8.8.n.>.5.8.8.8.8.n.g.l 8.n.D.G g d d d 7 d t d d g e g d g d ",
"e e e e e d d d d d d g d t d d t d d d d e d d 5 G Q 8.E.>.J 6 d g g g k g h d N g g g h h d d h g h g h h K h h g h d N k z h h h g g g d d d g d d k e d g g n g d z g d d g 7 G Q n.E.} G 5 t d e g d e t g t j j t d d d t g d t t d t g d g g h z k d d g ",
"d e d d e g z d g d g d e e d d t d d d g d d g g 7 x J R J q z z g g g g g k g h h n h h g h h h h g g g g h D D g h h z z z h K g h g h t d t g h t t d d d g q d d d d t t d g k v ` Q J q j d q e g d d d g d t g t d d h 6 d t e d e g d d k t h g e G d t ",
"d d e d e t e G d d g D g d d d d d d d d t h d g e l b R x h V N h g g g g g g h h g g h g g g z h k g g h h k z h V k z h h V N z k g k g g h D d d z t t t t t t g t d g d g k d l J 1.G e e q d d e d d d e t g d g g 7 g h z g d g g d d g g V g d h e k d ",
"e e e t g d g g g g d d t d t g z g g g g g d d t g l #.E l h k N g t g g d g g d h g h 8 g g g g h j g g h h z h h k z h g z V K O.h h h z q g h g g t 7 g d t t g C h g t g D g g z ` ` x d d e e e e d t d d g d h g K z g g z d q e g e d t d e t d d d d d ",
"d g e t t t g g g G d d d d d g d d d j t q g g g d l J Q x h h k k g h h g g h h g g g g g g g h z h g h h h k N V D k z D k V z h h h z h g t d g d d t d t h d t h k d h d D t h G 8.8.v n g t d d d t e g d z g h z h h g c d d d g d g d e d e d d g d h d ",
"j e e d d t t z j e d d d t g e t t z d d d k k d d l b Q c k h k g g h g g g g g g h g g g g g d d g h g h h k k t g d g h k N h z z 6 g d d g d g g d d d d d h t h K h h g h t g J 1.>.v q k g h d d g d t d d g g 4 d g d d e d d g k g z d d d d d d h D t ",
"d e h z e w h h d e g g d d z d d g h g d d h g h g l Q J c z h k g g h d g g t g h h g h g h g g g h h h h D O.t h d g g h g V t g t g t t g d g t t t d g d t g q t h k k g t t g v 9.w.G g V q d g d d t e d g k k t g d t t k g z d g z k V z K d g t e e d ",
"7 d d e d t 4 5 g d e k d t d e d w e t d t e z d t x 1.1.J k k k z g g g g h g h h h h g g g g g h g N k V k V g g g g g g g g g g g h z d d g t t t t g t d e t t t d C h t t g h c 8.n.z d e d g d d g d g g e k d e d g d d g t d d g k h g g t t e e t d e ",
"g d d d d j e g h q e d z d g z k z e d d d d g d d l J 8.J z V 5 h h g g h h h z g h z g g g g g h h z h V V N g g 4 g h g h h g h g g h g g d t t t t t q k t t d t g y k g d g g c R x d d k y d d d e g d d d t d t d d d d g d d g d e h g k d d d d g k d ",
"g d d d d d t d } k g d d t d d t q g g t d d g d d l 8.9.J z z 6 g g d g g h g h g g h g d g g g g h h k h N z g g h g g g g g h d g d g t g d g q > g d t d h d e g h N h d g d k j J l g d d t d d d g d d e e e d t k d d j d e d g d t d t d d d j D } 7 z ",
"d e 7 e e e t e d g e g d d d d d e w d d t d t h g x #.K.D h k g k h g g g g g g h z h g t d g h g h y h z V z k h g D g g g g h g g g g d g d g d t t t g t t t t h g h g g d g t j b x g d d d d d g g t d d t d g g d d d e d h k z h g d k t d g g d d d d ",
"e d t e t e g g d z g g e e d k d d d g d d e d h h z 8.=.h k D g h t g z V h t g g h z t g g t g d g 6 h h V h d h z K h h g g h H t h g t d d t g t t t q g t d d t t g d d g d d l v v j 1 d e d g g d t d t t t j d g g d d t d t t t d g d d d d g h g d d ",
"e d t d d d g g | g g e d t h d e d d g d d d g k g j 8.D k H g V h g g g z d g g h h g k g g h h g g g z g g g g g g g h z g h h N h h t d d g t d d h d d d t t d t g g g d g d g z R E j d g d t g h d d d d d d g d g d G t e d d g t d d d g g h g h g g d ",
"G d e t j d D [ j e d e t d e h g g d g d d d g h d g 8.z g h z h h g h g z d g g h g t d g g d g g h g g h h z h g d g g h t z k H z g d h g t g g g t g d d g t g g d e g t d g g c J R v d g d d h : d d d e g 7 d e d d d d d d e d d t d d g g N d d g g d ",
"d g h h w d j e d g e d e e d e k k g d d d t t d g j n.d h g g h 1 h h g g g g g d h d g 7 g V d g g g g g h h k h h h g t d h k z t d h d t t t d d d d d q d t e d g h k t d h g v E Q l d e d g q e d d d d 1 d z g g d d d d d d z g d g d t d g k d d d e ",
"G t g d e g > d d e g d t d j g d t d d d t d g d g j Q k 6 d d g g h h g g d g z h d g V g g g h t g G g g t h g h h g g g h h z k t y.t g d h k g d t z t t t h d g d g g g g g h l J R z g e d e d d h z g g K K g z d g d d g d g k g q d z z g d d d t t d ",
"e e e d d t t e e w k e d d d h t d d d d g e g d d j J z d g z g k g K g g h z g h d h g h g g g d t g h g g h k h h g d g D k t z g t d d n g d g d h h t g g q t t g g d g d d d l J Q l d d g e d d g t g z h h q z t g d d z g h g k d t d e d g d d d t d ",
"e w e w a e e e e e z t e e d t d t d d d d d d d z j v j z d g g d h h z a s s a a s z h g d g d g g h g g h z p.g g s g j z z z a s s a s a g s g s a a a a e a e e e e a s e a j x v E l g z d d d g d t h z z g d g a g a s j z [ h h t g d } g a s a a a e ",
"l l x x x c l x x l c l g z D G J J ] J ] } J K z j v R x j j D D d j j v v v b v v v x j j j j 4.z z ] } J z l l l l v v v z j c v x v v v J v J v x x x v Q b v c v x x v v G l v J >.Q v j D G G ] | G ] G z G z j c b E b Q J v Q c j z z j j l x v x x x v ",
"4.1.8.n.8.w.8.8.n.1.4.9.R E ` Q J E Q Q Q #.Q >.R R 1.4.>.Q Q ` R #.>.w.8.F.8.g.H.!.w.4.` Q E 1.>.1.R 4.Q R J v J b R 4.8.1.#.>.8.n.H.S.n.w.8.w.8.8.4.9.w.F.w.n.8.w.n.n.F.w.S.8.H.w.n.H.~.n.1.8.r.Q E E Q ` 8.9.8.R Q n.Q.!.H.S.n.n.n.>.#.1.E b v J n.H.Q.S.H.n.",
"s.=.s.s.C.s.5.s.s.j.j.H k t t h t t t t t h k h h z K V z h g h h N C R.C.C.D.D.D.I.P.p.D z z V V z h k h V G Q R n.8.F.W.D.>.8.8.n.n.n.n.8.>.8.8.8.5.] } n.n.8.8.8.4.8.n.8.w.>.8.n.8.8.H.} l j e e 7 7 e 7 7 g g g l H.H.D.W.n.n.8.x l a a j Q ` n.(.(.Q.P.C.C.",
"B B n h n k n n h h h N n n V C n n V n C n n n C n N N n N V k V n V u h n N V N V V N V N N V V y N N V V D Q >.F.8.} 5 d e g j d a g d g g g e a e e e g g z a g j 5 a e a a e j e e a j g j z e a a j a e e d a a e g j z g e e w e a a a g Q !.I.K 6 n h h ",
"n n N n n n n n n n h h h n C I n h N n C V n n N C N V V V n V h Z V V n V C N n C H N N V V n V V V Z n V h J >.8.v e w 2 e a a g a e g g g j v s a e j d j j j j 7 e e a a w e e a a e w g 5 a e d a j e e g e a g a e q e g z d e a a g a a z K.V N n n h h ",
"n n n h n n n h n n n h n V N n N n n V V o.N V N V N V n n N n V N n n n N V N n N V V V V V V C H V V I n V v R #.J z c d a g e e a a a g j j g a e w j j g h z a a a a a a a e a e e a a e d d e w a g a e a e e a e d a e e 5 e e e e a a l D Q k V h V n h ",
"n n n n n V n n n n n n h n h I o.V N V C N n n n N h N V V V h n N n h N n n n N V V V V N n V C V V V N u V c b Q x d g d a d g d s a e z d c g c 7 7 w } j g g j g d a e a e a a a e a g e a g e 7 a g g a a a a a a j j e a a a a g g d j j a ` k V n n n n ",
"n V h n n n n h C n h n V n V F V V n Z C V V N V N N N C V C u n k n n V n V V h V V C N n V Z n C C V h N C l ` Q x w d z g a e g d e a 7 j j g 7 e e e a e e a 1 a a e a e a e a a a e a a k g w g a a d g a 7 e G s e a s e a e e a g g j e g Q k N N n n n ",
"B C h n n n n V B Z n h n n n V V H C I H k Z C N V C C V n n n h n N V n n V u V C C N V V V Z H I n V C V C c J R x e j e z 5 e e a a a e a 5 w e a a e 7 e a e 7 e a a a e a a a e e e a d a a e a z g g g d d a a g e d a a a a d e a j g a a Q h n N n N C ",
"9 n V C n h n n n h h h n N h n V n Z C h V V I y V N V V N C N 3 N n n V N V N C V C V V n C V n Z V V V N V z Q R x s a j d j d a a d e w a a a s d e a e a g a e j e e d a e e e e e a e w g g d g c g d j G a e a a e a d a a a a e e e e a s Q n N n V V V ",
"Z n n h n n n n n n n n h n k n I C Z n n N N V n C C V V V V h V N k V h H N V n V N V N N C C I ..V V V C N z R ` J g e j g t j a a e e g a a z g a g a a a a a a e e e a e e e e a e e e a 2 e a j l g a z d j a a a a t a a g G a z a a a a a Q h N N V N V ",
"C V n k n n n n I h N N h n n N I I C N n n n C V Z h N C Z Z H n n N V V N C N N Z V C V Z Z I I Z C V C C C c J #.x a a j k s g j j a a g D g a g z a a a d e a a e e j s e e e a a e a e e a g e d j z c g g j a a a e a g a w } y.d g a e a s Q k n N N n B ",
"n n n n n n V n V n h n h n k V I B B N u n N B C V V C C n C N n N n N n n V V N V V N N H C X.I I n H C Z n v J R l d a a j j g a d g e a g z z g g z a j s a e e w e e s w a a a a e e a e a d k d g g g g g d a a e a a g g g j z g a a e a a R k V h V V N ",
"C n n n n n V n n k V n n n n N U N C n n V C n V V C I A V C n V N V V V n N N C H N N V H Z I I C V V V N V c Q J x a a s a a e a j g e e g a g g j g 7 a a e s a e a a a a e e a a e e e e e g j z g g g g z e e g a d e g g g j e e a 7 a e a Q h n N V n n ",
"n N n n n V V n n h V n n n n n N C C n n n B V N V C V V n V N n N C V n V n V C C N n n n ..C N n V V n h C z Q R l a g a a d g g j a a a 6 g a d z g d e e e e e g e z g e e e e e e e e e a g d d d g j a g a z e a a a g G g 7 e e e e a e a ~ k V N C n n ",
"h V n n k n h n n n V V n n N n n Z n n n N h V V N H H V V V C V V N V N n V V C C V N N H V V V N V N V N V c ^.8.J g g a g z a G g d a g g e g z g g a a e e e e e e a e e w e e a e e 5 e e e a d g g e a a a g 1 e a a a e a e 5 e e z a e g J n n N V n n ",
"n F V V n n n h n n V n n n N n N V n n V V V N C N N C V V N n V V V H 3 V C N N C B C H V h C N n V V V N N c ~ 8.J e a e d e s a g j g e a q j d g a j e e e a t e a e e 5 e e a a e e e e e e e a e g g a d e g e e e e a g g e e e e 7 e a e Q k n n N n N ",
"N N n n N n n n n V N N n F n n N V V C n V V C V V N N V N N V N V k N h n V V H Z Z Z V @.B Z N V n N N V C G ` 8.z a e a d g a g v a g a g g d g e g a e e e a t e 7 e j e e e e a a a e e a a g a a e g e e e a e e a a a a a a e e e w e e a R k n N V V N ",
"V C y V V N n n n I V N n N k N H V C C C N V V n V N V V N C N n V N h V V V H C L H N C H @.C N N V N V C N v #.>.l a e e a d a a a g a e a e a e a e a a g e a g t e d a e w a e a a g d a a a s a e e a e e e a e a a g D g a e e a e e a e g J N V n V N h ",
"n N k n k N V N n N V V C n k n V V n C n C V V N V C n p V N V V V N N N X.V N N Z 3 H h H I H V V V n n V C z R b l g a a g a s a ; a g a a a a e e e a a e a e d t t e g w e t a e g h a a e a e a a e a e e e e a a a G w e 2 e e a e e e z s x z N N n V N ",
"V V n n n n C V n I n C V n n n n n n V n n n N V V C V V N V N n A V N V I C C N V H B C C Z Z C N N V V @.z l b J x j d d g j a a a w j a a a a e w a a s a g d h h d j a e a e e g e a a e a e a 2 a c a a a e g s a a g a a a g e a e e j s l x j C n n V N ",
"C O.O.O.O.c.O.O.y.O.O.H o.K D V D K o.O.y.c.O.D z g g s s s s s s s g j g j j j j g z j j j j j j d g g s g l c Q R x j l j j v v x x v Q ] x x v l x v x c x x g g F K J J } v l s s g j j c Q Q Q } v J J c j s x l v J c x l x l g g j j j v v J x z V H O.o.",
"Q E J E Q 9.n.Q Q Q ` 8.` E v v v b R R Q E E R v v v l l l v J v v v b v Q J v v v E #.Q v v b v v J v v b b >.Q.w.#.E Q Q #.9.8.w.9.n.W.K.F.n.4.9.4.4.9.w.9.>.~ ] | =.Q 1.1.Q v x x v J J J E Q ` Q Q Q Q Q Q Q 8.w.8.n.4.n.8.w.>.Q #.Q R Q 4.n.n.4.Q Q Q Q Q ",
"t t t t t t t t t t t t t N ] 8.V g g g t t g z J R R ` n.8.n.8.H.S.H.n.W.W.H.w.w.9.S.F.w.w.w.w.S.n.F.n.9.8.F.E.^.~.n.} j g z 5.g.g.s.s.H.H.n.n.n.8.8.| s.n.g.s.z h u y q d t d c K #.E J G k t t t t h N d t z D p.8.s.g.s.| C.C.C.z k h h D =.g.C.G h d t h k ",
"h k k h h h k h h k h h t N n N h h h h k h t y g Q >.S.).w.H.Q.C.n.C.H.Y.H.H.g.s.n.8.n.n.n.n.n.C.n.n.s.8.8.g.8.5.J 7 g g h g g g g g t t k g h g t g e t d d g n C n h k h t t g k J H.G z h h h h N N n Z k N C k h h h d h 9 y y h h h h h h h k k n k x.H N ",
"k k h h k h k k t h h h n V k F n h h h h h h k N D Q F.W.Q G 5 h q h z h h g g h g g g h g g h g t g g h g g g t d g d g h h g h g g t h N h g g d g g t k t g p m n y n V t t g d z J c h h h h h n n V h h k C 1 N t h h h h h h h N h y k h t h N V k C V h ",
"h h k h k k h n N y y k N V V n N k h h h h k N Z h v Q #.v 7 g g n g z h h t g d g h g g g d d g g g h g g g g h g g h h g g h g g g g t k d d g d g d g g d g n n h y y K t z d g z b b k h k h h h h h k n n N t k k k n r y h h h h h k N h f f h k n V C y ",
"h k h n n F n V H k y k n V V V N h h h k k h V h k z R R c g h h g g h V h h g d g g g g h d g g g g g g g h t h g h h g g g g h g h h g d h g d q t d g h n d B n n n y g h d d g j b E h h k h h k k N k h h n h h h h k k H h h h h k h h k h k k h h h h h ",
"y h k N n n u C C k h h n C C N k h h k k h h h k N x J >.} D g h h h g h h t g g g t d k h g h g g g h V g g h h g g h h z g h d g g g h t h d d t g d h t t d C k n p y h z t d d j R c h h h C k h N N 4 h N u C C N F y h t h f k h h k h k k t k k k h h h ",
"k N O.V F n n h C k h k N C C N y N h h k h k h k k x #.>.J h h h k z h z t g g g g h h k K z h g g h t d d g g h h g h z h g d d d q g g g g g h g g d h g g g h h n p V h 8 g t d z b l h k h h k H k h h h t n y y k k o.N h h h h h h h H C h h k h h h h h ",
"k n N n V N k u V k h n K n n n h k h h h h h F h h v 1.4.~ C z g N q H k h g d h g g g h k C D h h g g g g d z C N k g h g k g g z g z g q h , t t g h h g d t h h n n g d h h g h z v v z N u h k h t h h h k h t k f h h h h d d h k k k h n k n h h k k N h ",
"k V V h N V n C h h h t h n o.N h h h h h h k h k y x 8.1.J V t d g h h g g d g g h k g g g d h V q h d g g d h k g h h h z g g g d g t h h d h d d d h g d h d t h n N M h k h N t e J R z n N h H h h h h h h h h t h h h h N d h d h h h y n n h F k k N k h ",
"h h h f k h h r t h h y h N n h h h h h h k k h k k l Q 9.G t d g g g h t h g g d g h d h d g g K t g d g h g g h z h k h g h g h g t h g g g g d t g d d d g d t n N k g h k h h t z #.J z h t n h r k k h h k h k h h h h h f d h h k h y k h h h D k h N N k ",
"h h C k h h h h r y y h h h C k h h h k k h h k h k z J Q D g g g g z h g k g h k h g g h g d t k k g d g 6 g h V h h g h h h g h y.g h z h z h g h h g g h g g g h h N k h C h g t j J v z k k n k h h h h h h h h h h t k h h h d h y k [ h n h H , h h k h h ",
"h h h h h h k k h k h h h h k k h k h h h k h h N h z v Q l g h g D g g g h h h g h h g h q g n k g g g g d g h g g g g h z k k h C h h h h h h h h k V t g g h t h z q d d g 5 t d j v J z h h h h k f f h y f h k h h h O.h h h n V h h h h y h h h h N k k h ",
"k h h h h h h h h k k k h h h h h k k N k h y h k k z n.#.l d g g h d g g h k  .h h h g h d g h h d h d h t z g t h g g g h h k h z h g g g d h k h k h h d g d t h t g h t d t t g j b b z k h N t k h h f f h k N k V h n h y y V k t h h t y k k k V n h h k ",
"k h h h k h k t h h h k h n h h k h h k C h h h h h D #.#.l d g d g g g h N k k g h h h h h g g t h h z g k N z h h h g d d d g h g g g g g h h h h k k g g g d d t t g t d d t d t j b Q z h h h k k h h h k y V V h N t k t y y y t h h h h k h k O.V h k N k ",
"N h h h h h n h h n h h h h N h k h h h k h h h k k z 4.#.j t d g g g z g z g g h k h h g z d 6 h g g d h k N V d 6 g d g g g t g g d g g d g g z g h k t h g d d g d q q d g g d g l ` J z h h k k h V N n n h V n n h f y k h h h h k k h t k N N k y N N k C ",
"h N h t h h k h h k h h N h h h h 6 h N h h h h h h z >.J g d d g h g g g q g g g g h g g g h g g g d d d g h h g d g g g g g d d d g d g g g k k t k h g g t h d g d d g d d d t d l R R l h N h h h N C N V t h h h t h h k k h k f h h t h 4 C C f k N h C n ",
"N N h h h h k h y h k h k k t h n h h h h h h h k h h >.j t t g h g d g d h q h g k g h h h g g g g d d d z h k g d h g g g d d t d d g g d h N z k k d d h d t g t g t g d t k t g j R J z h h h h k N h 3 h t f h h h h t h h k h h f h N y 9 y t N V C N k N ",
"n V h h h t k h h k k k k h t h k h n h y h k h k N k Q g g d g k g g h h g z k D g h h h g g d h h h g h k k t h g g d g g d g g g d g g g g N k k t g h g g d t  .g V g 5 t t t h l v J z h h h h h k y h h h h t d h t d N C N h F h h h t t h t N n n N C V ",
"h h h h k y h h h k h N k h k k k h k h h h h k h 3 z b z h d g h d g h d h z g h g g h h h g g g t g t g d t d g g g g g d d d g V g t t d d g h g g d t d t g k d t t d g d d t g l J v x h k h k k k h H h h h h h h h t h k V H 6 h h y f h h n V N V V n k ",
"a a a s s g k D h k h h h h h k h h h k k h h k h D j b j z g g g h g k O.d g g t h g g h d t g g j a a a a a a a s z g d d t g 7 d K g e e e a e a a a a s e a a a a j z V [ } k j x >.Q J z z F O.O. .[ O.D O.O.[ [ [ O.y.O.D 4 O.K  .O.[ O. .t y.c.O.O.K z g ",
"v v v v b b v j z V [ [ O.O.i.[ O.[ y.i.K K O.F h j z E x j D D ] K O.V [  . . . . .G K K  .] j g x x v v c v x c v c j j z K g z j j l l l x v x v x v c v x x x v v v Q 8.8.>.R R >.n.E.n.#.8.4.>.>.R >.Q >.1.1.` Q J R J J ` Q >.>.` J J R R R ` >.8.>.` #.v "
};
